In [1]:
import numpy as np
from qiskit import QuantumCircuit, Aer, transpile
from qiskit.visualization import plot_bloch_multivector
from qiskit.quantum_info import Statevector
from IPython.display import display
from qiskit.tools.visualization import plot_histogram

sim = Aer.get_backend("aer_simulator")


# Q14 Xを2回作用させるとIとなることを行列計算とゲートの実行で確認せよ。Y, Z, Hについても同様に確認せよ。

## 解答

In [10]:
"""Xゲート"""
# 行列計算
# numpy ndarrayを用いて行列を定義
x_matrix = np.array([[0., 1.], [1., 0.]])
xx_matrix = np.matmul(x_matrix, x_matrix)
print(f"行列計算 X*X = \n{xx_matrix}")
np.testing.assert_allclose(actual=xx_matrix, desired=np.identity(2), atol=1e-7)

# ゲートの実行


def get_circuit_as_unitary_op(qc):
    """量子回路をユニタリ行列として返す関数"""
    unitary_sim = Aer.get_backend("unitary_simulator")
    unitary_op = unitary_sim.run(circuits=qc).result().get_unitary()
    return unitary_op

# 1量子ビットの量子回路を作成
qc = QuantumCircuit(1)
# Xゲートを二回連続で作用
qc.x(qubit=0)
qc.x(qubit=0)
unitary_op = get_circuit_as_unitary_op(qc=qc)
print(f"ゲートの実行 X*X = \n{unitary_op.data}")
np.testing.assert_allclose(actual=unitary_op, desired=np.identity(2), atol=1e-7)

行列計算 X*X = 
[[1. 0.]
 [0. 1.]]
ゲートの実行 X*X = 
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [11]:
"""Yゲート"""
# 行列計算
y_matrix = np.array([[0., -1j], [1j, 0.]])
yy_matrix = np.matmul(y_matrix, y_matrix)
print(f"行列計算 Y*Y = \n{yy_matrix}")
np.testing.assert_allclose(actual=yy_matrix, desired=np.identity(2), atol=1e-7)

# ゲートの実行
qc = QuantumCircuit(1)
qc.y(qubit=0)
qc.y(qubit=0)
unitary_op = get_circuit_as_unitary_op(qc=qc)
print(f"ゲートの実行 Y*Y = \n{unitary_op.data}")
np.testing.assert_allclose(actual=unitary_op, desired=np.identity(2), atol=1e-7)

行列計算 Y*Y = 
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
ゲートの実行 Y*Y = 
[[1.-0.j 0.-0.j]
 [0.+0.j 1.+0.j]]


In [12]:
"""Zゲート"""
# 行列計算
z_matrix = np.array([[1., 0.], [0., -1.]])
zz_matrix = np.matmul(z_matrix, z_matrix)
print(f"行列計算 Z*Z = \n{zz_matrix}")
np.testing.assert_allclose(actual=zz_matrix, desired=np.identity(2), atol=1e-7)

# ゲートの実行
qc = QuantumCircuit(1)
qc.z(qubit=0)
qc.z(qubit=0)
unitary_op = get_circuit_as_unitary_op(qc=qc)
print(f"ゲートの実行 Z*Z = \n{unitary_op.data}")
np.testing.assert_allclose(actual=unitary_op, desired=np.identity(2), atol=1e-7)

行列計算 Z*Z = 
[[1. 0.]
 [0. 1.]]
ゲートの実行 Z*Z = 
[[1.+0.j 0.+0.j]
 [0.-0.j 1.-0.j]]


In [13]:
"""Hゲート"""
# 行列計算
h_matrix = np.array([[1., 1.], [1., -1.]]) / np.sqrt(2.)
hh_matrix = np.matmul(h_matrix, h_matrix)
print(f"行列計算 H*H = \n{hh_matrix}")
np.testing.assert_allclose(actual=hh_matrix, desired=np.identity(2), atol=1e-7)

# ゲートの実行
qc = QuantumCircuit(1)
qc.h(qubit=0)
qc.h(qubit=0)
unitary_op = get_circuit_as_unitary_op(qc=qc)
print(f"ゲートの実行 H*H = \n{unitary_op.data}")
np.testing.assert_allclose(actual=unitary_op, desired=np.identity(2), atol=1e-7)

行列計算 H*H = 
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]
ゲートの実行 H*H = 
[[1.-6.1232340e-17j 0.+6.1232340e-17j]
 [0.+6.1232340e-17j 1.-1.8369702e-16j]]


## 解説
パウリ行列とアダマール行列の共通の性質は、それらがユニタリ行列且つエルミート行列であることである。すなわち、$A^{\dagger}A = I$（ユニタリ行列）、$A^{\dagger}=A$（エルミート行列）を満たす。この二つの性質から、$AA=I$を満たすことを定性的にも示すことができる。

一般にゲートとしての行列は、エルミート行列であることは求められない一方でユニタリ行列であることは求められる。これは、下記のように確率の保存から要請される。まず1量子ビットの任意の状態ベクトルを$|\Psi \rangle$とすると、確率の合計は1であることから
$$
\sum_{i=\alpha, \beta} |\langle i | \Psi \rangle|^2 = 1
$$
が要請される。ただし、$|i\rangle\ (i=\alpha, \beta)$は任意の正規直交基底とする。あるゲート$U$を作用させた状態 $|\Psi^{\prime} \rangle = U |\Psi \rangle$もこの関係式を満たすべきであり、
$$
\sum_{i=\alpha, \beta} |\langle i | \Psi^{\prime} \rangle|^2 = \sum_{i=\alpha, \beta} |\langle i | U | \Psi \rangle|^2 = \sum_{i=\alpha, \beta} \langle \Psi | U^{\dagger} |i \rangle \langle i | U | \Psi \rangle = \langle \Psi | U^{\dagger} U | \Psi \rangle
$$
上式の最右の項が常に1となるには、$U^{\dagger}U = I$を満たす必要がある。

## 参考資料
- Qiskitテキストブック https://qiskit.org/textbook/ja/ch-states/single-qubit-gates.html#1.-%E3%83%91%E3%82%A6%E3%83%AA%E3%82%B2%E3%83%BC%E3%83%88-
- Qiskitテキストブック https://qiskit.org/textbook/ja/ch-gates/proving-universality.html#2.2-%E3%83%A6%E3%83%8B%E3%82%BF%E3%83%AA%E3%83%BC%E8%A1%8C%E5%88%97%E3%81%A8%E3%82%A8%E3%83%AB%E3%83%9F%E3%83%BC%E3%83%88%E8%A1%8C%E5%88%97-